language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t araxis/docker-react -f Dockerfile.dev .

#script:
#- docker run araxis/docker-react nmp run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-460576859467"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
